# Government of Canada
+ 03/26/2024 - [(Health Canada) Supervised consumption sites](https://health-infobase.canada.ca/supervised-consumption-sites/)
+ 03/27/2024 - [(Public Health Agency of Canada) Opioid- and Stimulant-related Harms in Canada](https://health-infobase.canada.ca/substance-related-harms/opioids-stimulants/)
+ 12/15/2023 - [(Public Health Agency of Canada) Modelling opioid-related deaths during the overdose crisis](https://www.canada.ca/en/health-canada/services/opioids/data-surveillance-research/modelling.html)
+ 01/19/2022 - [(Statistics Canada) - Significant factors associated with problematic use of opioid pain relief medications among the household population, Canada, 2018](https://www150.statcan.gc.ca/n1/pub/82-003-x/2021012/article/00002-eng.htm)
+ 07/15/2021 - [(Statistics Canada) Study: Understanding opioid overdoses in Simcoe Muskoka, Ontario, 2018 and 2019](https://www150.statcan.gc.ca/n1/daily-quotidien/210715/dq210715b-eng.htm)
+ 07/15/2021 - [(Statistics Canada) Understanding opioid overdoses in Simcoe Muskoka, Ontario](https://www150.statcan.gc.ca/n1/pub/11-627-m/11-627-m2021060-eng.htm)
+ 02/17/2021 - [(Statistics Canada) Statistics Canada British Columbia Opioid Overdose Analytical File: Technical Report](https://www150.statcan.gc.ca/n1/pub/11-633-x/11-633-x2021003-eng.htm)
+ 04/10/2019 - [(Statistics Canada) Employment and Social Assistance Receipt Among Overdose Fatalities in British Columbia ](https://www150.statcan.gc.ca/n1/pub/11-626-x/11-626-x2019004-eng.pdf)
+ 10/17/2018 - [(Statistics Canada) Social and economic characteristics of those experiencing hospitalizations due to opioid poisonings](https://www150.statcan.gc.ca/n1/pub/82-003-x/2018010/article/00002-eng.htm)

# CBC
+ 04/11/2024 - [Contrasting studies show possible impact of safer supply in B.C.](https://www.cbc.ca/news/canada/british-columbia/bc-safer-supply-opioid-studies-1.7170468)
+ 08/29/2022 - [Ontario's opioid crisis is killing men in the construction industry](https://www.cbc.ca/news/canada/thunder-bay/opioid-crisis-construction-industry-ontario-1.6563811)
+ 08/23/2022 - [Opioid deaths in Ontario rose dramatically in pandemic's first 2 years compared to 2019, early data shows](https://www.cbc.ca/news/canada/sudbury/opioid-crisis-ontario-pandemic-1.6559379)
+ 08/16/2022 - [Over 10,000 people in B.C. have died due to toxic drugs since health emergency was declared in 2016: coroner](https://www.cbc.ca/news/canada/british-columbia/bc-overdose-deaths-june-2022-fatalities-decreasing-coroner-says-1.6552558)

# Other
+ 05/22/2024 - [(PHO) Interactive Opioid Tool](https://www.publichealthontario.ca/en/data-and-analysis/substance-use/interactive-opioid-tool)
+ 04/30/2024 - [(OPDRN) Ontario Opioid Indicator Tool](https://odprn.ca/ontario-opioid-indicator-tool/)
+ 04/15/2024 - [(CMAJ) Open Access Opioid-related deaths between 2019 and 2021 across 9 Canadian provinces and territories](https://www.cmaj.ca/content/196/14/E469)
+ 11/23/2023 - [(GoO) Narcotics Monitoring System](https://www.ontario.ca/page/narcotics-monitoring-system)
+ 09/15/2022 - [(BCCDC) Unregulated Drug Poisoning Crisis Dashboard](https://public.tableau.com/app/profile/bccdc/viz/UnregulatedDrugPoisoningCrisisDashboard/Introduction)
+ 09/21/2018 - [(Science) Changing dynamics of the drug overdose epidemic in the United States from 1979 through 2016](https://www.science.org/doi/10.1126/science.aau1184)
